### ISSUE TITLE
Feedback Mark

### ISSUE THREAD

**Issue by YankInSchweiz** [w201rdada/portfolio-mpaluta#2]
As I understand your big idea, the objective of the study is to provide a democratic way of handling complex social and ethical issues through the use of broad, optional survey's done in a scientific method to help policy makers decide challenging questions.  This to me is a very big idea and ties together our field of study, current technological trends and difficult but necessary answers needed as we move down our current path.

Awesome intro, woke me up better than my coffee.  Very well thought out idea and strong story telling to convey the crux of the problem and alternative interpretation of the tradeoffs a rational individual would make in comparison to the decisions necessary for public policy.  

It may be beneficial to add in the conclusion some of the potential complex response the survey could produce.  If for example on geo gives answer A and another answer B, how does a national policy bridge the divide?  What if the majority goes in favor of individualism, how does a policy maker go forward, by stepping in and claiming they know better than the mass.  The risk of putting something up for a democratic vote is that the policy makers must then exercise the wishes of the population, which is not a good or bad thing, but the risk is it goes against a philosophical/hypothetical belief in the greater good.  When dealing with a sample size of 1 (yourself), statistics be damned!  This is a very entertaining (meant in a positive way) Big Idea which i will puzzle over for parts of the remainder of my day, thanks.

**Comment by mpaluta** [comment]
I tried to build up the parts you and others positively highlighted while also sharpening the thesis and scope. I agree regarding the complexities and in my newest revision I went into a number of drawbacks of democratization and I fleshed out more details on the implementation strategy.

Thank you for the feedback. I'm going to close this issue for now.
